### ISSUE TITLE
buildRequestURL should accept a state value

### ISSUE THREAD

**Issue by justindh** [karnthis/esiil#2]
maybe something like this

`  
buildRequestURL(scopes = [], state = '') {
    const useScope = (this.masterScopes.length > 0) ? this.masterScopes : scopes
    if (useScope.length == 0) throw new Error('must have at least 1 scope selected')
    return [`https://login.eveonline.com/oauth/authorize/?response_type=code`,
    `redirect_uri=${encodeURI(this.callbackURL)}`,
    `client_id=${this.clientID}`,
    `scope=${useScope.join(' ')}`,
    `state=${state}`].join('&')
  }
`

**Comment by karnthis** [comment]
This is a good suggestion. I don't personally use state, so it did not occur to me to include it.

**Comment by karnthis** [comment]
Now available on the Alpha branch

**Comment by justindh** [comment]
Works :)

**Comment by karnthis** [comment]
Now available in v0.1.2, closing issue
