### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by okuRaku** [karnthis/esiil#3]
I figure this is probably an issue with my setup, but I'm curious is this currently working?  In the example, there seems too be a minor typo (Auth vs auth) but correcting that I still see bad behavior, which is when it goes to hit the url the character_id is undefined.   I've been trying to debug myself, but figured I'd ask, just in case.

I'm just trying to run it in a simple app.js via node.

Thanks

**Comment by karnthis** [comment]
Hi there, thanks for sharing your issue! To answer your question, yes it does work but there are a lot of bugs getting worked out. This is still an alpha build and we are always looking for places to improve.

You are right about the typo, I will add that to the in-progress update. I will admit that writing documentation is not my strong suit.

Could you please share the code you are using that is giving you the error?

**Comment by okuRaku** [comment]
Thanks for the quick response!  Well honestly it's just what's in the example you gave, but I tried to log something (randomly picked corphistory) to console.   I can see in the log the url it tries to hit, but character_id is 'undefined'

**Comment by okuRaku** [comment]
Perhaps I should mention, I'm using my client id / secret from the dev site.   So I didn't think there was an issue there (I got it working in postman earlier)

**Comment by karnthis** [comment]
Ah I see. The ReadMe example is not the best, but what you are running into is the `char.corpHistory()` expects a character ID to be passed. an example would be `char.corpHistory(92014574)`. Let me know if that works better for you.

**Comment by okuRaku** [comment]
Oh!  Wow okay...  I need to understand better how to do an auth then, to get my character id and all that.   I'll start over.   Thanks again for the quick response!

**Comment by karnthis** [comment]
Do you use Discord or Slack at all?
